### ISSUE TITLE
How to replicate the figure 3?

### ISSUE THREAD

**Issue by wenjiyanli** [upperr/DLSM#2]
Hi, I would like to visualize the random factors γi and replicate figure 3. I see the code and find that γi is a vector and not like a degree is a value, so I don't understand how to visualize γi and degree together. How could I do it?

**Comment by upperr** [comment]
Hi! In figure 3, each value of the random factors is obtained by averaging the elements of the vector over all dimensions.

**Comment by wenjiyanli** [comment]
@upperr Hi! Thanks for your kind reply! I also want to know if the results of the random factors are saved in the "model.theta_decoder" list? I fetch the gamma, take the reverse and take the average over all dimensions, but the value may be too large, and the density plot is weird. I don't know where I am wrong (I attached the code and the output below). Thanks a lot!
```
qul_results = np.load('data/qual_political0_dlsm_32_64_128_50_100_50.npz')
np.load.__defaults__= (None, False, True, 'ASCII')
theta_decoder = qul_results['theta_decoder']

#γi
random_node_effect1 = 1 / theta_decoder[1] # reverse
print(random_node_effect1)            #(1222, 50)
gamma_draw = random_node_effect1.mean(axis = 1) #averaging over all dimensions

#degree
dataset_str = 'political'
adj, features, feature_presence, directed = load_data(dataset_str)
adj = adj - sp.dia_matrix((adj.diagonal()[np.newaxis, :], [0]), shape = adj.shape)
degrees_out = np.transpose(adj.sum(axis = 1).A)[0];print(degrees_out)
 

# Draw Plot
plt.figure(figsize=(6,4), dpi= 80)
fig = sns.kdeplot(gamma_draw, shade=True, color="r", label="1/γ", alpha=.5)
fig = sns.kdeplot(degrees_out, shade=True, color="g", label="out_degree", alpha=.5)
plt.title('Density Plot of gamma and out degree', fontsize=12)
plt.legend()
plt.show()

```
[[  9101.525   11236.38    10345.1455 ...  11323.76     8558.132
   10995.634 ]
 [  4595.2046   5422.9736   4560.4414 ...   4855.967    4870.5894
    4767.8564]
 [  2469.2847   2539.1375   2416.7593 ...   2172.3782   2287.5913
    2233.693 ]
 ...
 [132995.02   144166.64   152915.11   ... 146875.5    151077.61
  145370.66  ]
 [  5776.861    8031.7773   6371.006  ...   5827.636    6511.214
    7022.1177]
 [  6252.635    5860.7026   7072.008  ...   7646.9985   8043.2896
    6208.9834]]
[15 43  3 ...  1  8  1]
![image](https://user-images.githubusercontent.com/43998947/221116101-60b0d776-3fcf-4666-b874-84023afe7ee6.png)

**Comment by upperr** [comment]
@wenjiyanli Hi! Thanks for your effort to replicate Fig. 3. To avoid the tail of gamma being too long to visualize, we need to adjust the values of reverse gamma to the same scale as out-degrees. You can use the following code:
```python
gamma_draw = gamma_draw / (np.max(gamma) / np.max(degrees_out))
```
In this way, the maximal value of reverse gamma is rescaled to the same as that of out-degrees, while still keeping the density distribution of reverse gamma unchanged.

The density distributions of random factors in our paper are drawn using R, rather than python. The R code is given as follows:
```R
library(ggplot2)
library(latex2exp)

mytheme <- theme_minimal()+
  theme(
    panel.grid.major.y=element_blank(),
    panel.grid.minor.y=element_blank(),
    panel.grid.major.x=element_blank(),
    panel.grid.minor.x=element_blank(),
    axis.line.y=element_line(linetype=1,color='grey'),
    axis.line.x=element_line(linetype=1,color='grey'),
    axis.ticks = element_line(linetype=2,color='grey'),
    legend.title = element_blank(),
    legend.background = element_rect(fill = "gray90", size=0.5, color='white'),
    legend.text=element_text(size=15),
    legend.position = c(0.7, 0.8),
    legend.direction = "horizontal",
    axis.text = element_text(size = 10),
    axis.title.y = element_text(size = 12),
    axis.title.x = element_blank()
  )

### political ###
gamma = scan('data/gamma_political.txt')
outdegree = scan('data/outdegree_political.txt')
dat1 = data.frame(x = c(gamma / (max(gamma) / max(outdegree)), outdegree), label = factor(c(rep(1, length(gamma)), rep(2, length(outdegree)))))
ggplot(dat1, aes(x = x)) +
  geom_density(data = dat1, aes(color = factor(label), fill = factor(label)), alpha = 0.3, bw = 20) +
  scale_fill_discrete(labels = c(expression(1/gamma), 'out-degree')) +
  scale_colour_discrete(labels = c(expression(1/gamma), 'out-degree')) +
  mytheme
```
Here the data 'gamma_political.txt' is obtained from the saved gamma in the 'model.theta_decoder' list, which has been preprocessed by averaging over all dimensions and then taking the reverse.

Hope this would help you!

**Comment by wenjiyanli** [comment]
Thanks! That helps me a lot! Best regards!
